/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	transformationv1beta1 "github.com/greatlazyman/apiserver/pkg/apis/transformation/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// Base64Lister helps list Base64s.
// All objects returned here must be treated as read-only.
type Base64Lister interface {
	// List lists all Base64s in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*transformationv1beta1.Base64, err error)
	// Base64s returns an object that can list and get Base64s.
	Base64s(namespace string) Base64NamespaceLister
	Base64ListerExpansion
}

// base64Lister implements the Base64Lister interface.
type base64Lister struct {
	listers.ResourceIndexer[*transformationv1beta1.Base64]
}

// NewBase64Lister returns a new Base64Lister.
func NewBase64Lister(indexer cache.Indexer) Base64Lister {
	return &base64Lister{listers.New[*transformationv1beta1.Base64](indexer, transformationv1beta1.Resource("base64"))}
}

// Base64s returns an object that can list and get Base64s.
func (s *base64Lister) Base64s(namespace string) Base64NamespaceLister {
	return base64NamespaceLister{listers.NewNamespaced[*transformationv1beta1.Base64](s.ResourceIndexer, namespace)}
}

// Base64NamespaceLister helps list and get Base64s.
// All objects returned here must be treated as read-only.
type Base64NamespaceLister interface {
	// List lists all Base64s in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*transformationv1beta1.Base64, err error)
	// Get retrieves the Base64 from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*transformationv1beta1.Base64, error)
	Base64NamespaceListerExpansion
}

// base64NamespaceLister implements the Base64NamespaceLister
// interface.
type base64NamespaceLister struct {
	listers.ResourceIndexer[*transformationv1beta1.Base64]
}
