//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	config "github.com/GreatLazyMan/simplescheduler/pkg/apis/config"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CoschedulePluginArgs)(nil), (*config.CoschedulePluginArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CoschedulePluginArgs_To_config_CoschedulePluginArgs(a.(*CoschedulePluginArgs), b.(*config.CoschedulePluginArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CoschedulePluginArgs)(nil), (*CoschedulePluginArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CoschedulePluginArgs_To_v1_CoschedulePluginArgs(a.(*config.CoschedulePluginArgs), b.(*CoschedulePluginArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_CoschedulePluginArgs_To_config_CoschedulePluginArgs(in *CoschedulePluginArgs, out *config.CoschedulePluginArgs, s conversion.Scope) error {
	if err := metav1.Convert_Pointer_string_To_string(&in.DeploymentName, &out.DeploymentName, s); err != nil {
		return err
	}
	if err := metav1.Convert_Pointer_string_To_string(&in.Image, &out.Image, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_CoschedulePluginArgs_To_config_CoschedulePluginArgs is an autogenerated conversion function.
func Convert_v1_CoschedulePluginArgs_To_config_CoschedulePluginArgs(in *CoschedulePluginArgs, out *config.CoschedulePluginArgs, s conversion.Scope) error {
	return autoConvert_v1_CoschedulePluginArgs_To_config_CoschedulePluginArgs(in, out, s)
}

func autoConvert_config_CoschedulePluginArgs_To_v1_CoschedulePluginArgs(in *config.CoschedulePluginArgs, out *CoschedulePluginArgs, s conversion.Scope) error {
	if err := metav1.Convert_string_To_Pointer_string(&in.DeploymentName, &out.DeploymentName, s); err != nil {
		return err
	}
	if err := metav1.Convert_string_To_Pointer_string(&in.Image, &out.Image, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_CoschedulePluginArgs_To_v1_CoschedulePluginArgs is an autogenerated conversion function.
func Convert_config_CoschedulePluginArgs_To_v1_CoschedulePluginArgs(in *config.CoschedulePluginArgs, out *CoschedulePluginArgs, s conversion.Scope) error {
	return autoConvert_config_CoschedulePluginArgs_To_v1_CoschedulePluginArgs(in, out, s)
}
