/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	scheme "github.com/GreatLazyMan/simplescheduler/pkg/apis/client/clientset/versioned/scheme"
	v1 "github.com/GreatLazyMan/simplescheduler/pkg/apis/crd/simpleio/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// QueuesGetter has a method to return a QueueInterface.
// A group's client should implement this interface.
type QueuesGetter interface {
	Queues() QueueInterface
}

// QueueInterface has methods to work with Queue resources.
type QueueInterface interface {
	Create(ctx context.Context, queue *v1.Queue, opts metav1.CreateOptions) (*v1.Queue, error)
	Update(ctx context.Context, queue *v1.Queue, opts metav1.UpdateOptions) (*v1.Queue, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, queue *v1.Queue, opts metav1.UpdateOptions) (*v1.Queue, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Queue, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.QueueList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Queue, err error)
	QueueExpansion
}

// queues implements QueueInterface
type queues struct {
	*gentype.ClientWithList[*v1.Queue, *v1.QueueList]
}

// newQueues returns a Queues
func newQueues(c *SimpleV1Client) *queues {
	return &queues{
		gentype.NewClientWithList[*v1.Queue, *v1.QueueList](
			"queues",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.Queue { return &v1.Queue{} },
			func() *v1.QueueList { return &v1.QueueList{} }),
	}
}
