apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simplecontroller
  name: simplecontroller
  namespace: greatlazyman-system
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: simplecontroller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplecontroller
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - simplecontroller
            namespaces:
            - greatlazyman-system
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - simplecontroller
        image: greatlazyman/simplecontroller:xxx
        imagePullPolicy: IfNotPresent
        name: controller
        resources:
          limits:
            cpu: 2
            memory: 200Mi
          requests:
            cpu: 300m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: simplecontroller
      serviceAccountName: simplecontroller
      terminationGracePeriodSeconds: 30
