// Copyright 2023 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/GreatLazyMan/simplecontroller/pkg/apis/client/clientset/versioned"
	internalinterfaces "github.com/GreatLazyMan/simplecontroller/pkg/apis/client/informers/externalversions/internalinterfaces"
	v1 "github.com/GreatLazyMan/simplecontroller/pkg/apis/client/listers/simplecontroller/v1"
	simplecontrollerv1 "github.com/GreatLazyMan/simplecontroller/pkg/apis/simplecontroller/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SimpleJobInformer provides access to a shared informer and lister for
// SimpleJobs.
type SimpleJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SimpleJobLister
}

type simpleJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSimpleJobInformer constructs a new informer for SimpleJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSimpleJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSimpleJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSimpleJobInformer constructs a new informer for SimpleJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSimpleJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GreatlazymanV1().SimpleJobs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GreatlazymanV1().SimpleJobs(namespace).Watch(context.TODO(), options)
			},
		},
		&simplecontrollerv1.SimpleJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *simpleJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSimpleJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *simpleJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&simplecontrollerv1.SimpleJob{}, f.defaultInformer)
}

func (f *simpleJobInformer) Lister() v1.SimpleJobLister {
	return v1.NewSimpleJobLister(f.Informer().GetIndexer())
}
