apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: simplecsi-hostpath-sc
provisioner: hostpath.simplecsi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  basepath: "/data/"
