apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: apiserver-example
spec:
  http:
  - name: example
    match:
      paths:
      - /apiserver
      - /apiserver/*
    upstreams:
    - name: apiserver
