apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: simplecni
  name: simplecni
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: simplecni
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplecni
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - command:
        - /usr/local/bin/simplecni
        - --ip-masq
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: EVENT_QUEUE_DEPTH
          value: "5000"
            #- name: "IPTABLES"
            #  value: "nf_tables"
        image: simplecni:v0.0.1
        imagePullPolicy: IfNotPresent
        name: simplecni
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/simplecni
          name: run
        - mountPath: /var/run/wireguard
          name: wireguardsock
        - mountPath: /etc/simplecni/
          name: simplecni-cfg
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /dev/net
          name: devnet
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - args:
        - -r
        - /cni/bin
        - /opt/cni/
        command:
        - cp
        image: simplecni:v0.0.1
        imagePullPolicy: IfNotPresent
        name: install-cni-plugin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/cni/bin
          name: cni-plugin
      - args:
        - -f
        - /etc/simplecni/cni-conf.json
        - /etc/cni/net.d/10-simplecni.conflist
        command:
        - cp
        image: simplecni:v0.0.1
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cni/net.d
          name: cni
        - mountPath: /etc/simplecni/
          name: simplecni-cfg
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: simplecni
      serviceAccountName: simplecni
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /run/simplecni
          type: ""
        name: run
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: cni-plugin
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni
      - configMap:
          defaultMode: 420
          name: simplecni-cfg
        name: simplecni-cfg
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /dev/net
          type: ""
        name: devnet
      - hostPath:
          path: /var/run/wireguard
          type: ""
        name: wireguardsock
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

