// Copyright 2023 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "github.com/GreatLazyMan/simplecontroller/pkg/apis/client/clientset/versioned/scheme"
	v1 "github.com/GreatLazyMan/simplecontroller/pkg/apis/simplecontroller/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SimpleJobsGetter has a method to return a SimpleJobInterface.
// A group's client should implement this interface.
type SimpleJobsGetter interface {
	SimpleJobs(namespace string) SimpleJobInterface
}

// SimpleJobInterface has methods to work with SimpleJob resources.
type SimpleJobInterface interface {
	Create(ctx context.Context, simpleJob *v1.SimpleJob, opts metav1.CreateOptions) (*v1.SimpleJob, error)
	Update(ctx context.Context, simpleJob *v1.SimpleJob, opts metav1.UpdateOptions) (*v1.SimpleJob, error)
	UpdateStatus(ctx context.Context, simpleJob *v1.SimpleJob, opts metav1.UpdateOptions) (*v1.SimpleJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SimpleJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SimpleJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SimpleJob, err error)
	SimpleJobExpansion
}

// simpleJobs implements SimpleJobInterface
type simpleJobs struct {
	client rest.Interface
	ns     string
}

// newSimpleJobs returns a SimpleJobs
func newSimpleJobs(c *GreatlazymanV1Client, namespace string) *simpleJobs {
	return &simpleJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the simpleJob, and returns the corresponding simpleJob object, and an error if there is any.
func (c *simpleJobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SimpleJob, err error) {
	result = &v1.SimpleJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simplejobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SimpleJobs that match those selectors.
func (c *simpleJobs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SimpleJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SimpleJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simplejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested simpleJobs.
func (c *simpleJobs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("simplejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a simpleJob and creates it.  Returns the server's representation of the simpleJob, and an error, if there is any.
func (c *simpleJobs) Create(ctx context.Context, simpleJob *v1.SimpleJob, opts metav1.CreateOptions) (result *v1.SimpleJob, err error) {
	result = &v1.SimpleJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("simplejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(simpleJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a simpleJob and updates it. Returns the server's representation of the simpleJob, and an error, if there is any.
func (c *simpleJobs) Update(ctx context.Context, simpleJob *v1.SimpleJob, opts metav1.UpdateOptions) (result *v1.SimpleJob, err error) {
	result = &v1.SimpleJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("simplejobs").
		Name(simpleJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(simpleJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *simpleJobs) UpdateStatus(ctx context.Context, simpleJob *v1.SimpleJob, opts metav1.UpdateOptions) (result *v1.SimpleJob, err error) {
	result = &v1.SimpleJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("simplejobs").
		Name(simpleJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(simpleJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the simpleJob and deletes it. Returns an error if one occurs.
func (c *simpleJobs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simplejobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *simpleJobs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simplejobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched simpleJob.
func (c *simpleJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SimpleJob, err error) {
	result = &v1.SimpleJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("simplejobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
