---
apiVersion: v1
kind: Service
metadata:
  name: my-webhook
  labels:
    app: my-webhook
spec:
  ports:
  - port: 443
    targetPort: 9443
    name: https-my-webhook
  selector:
    app.kubernetes.io/name: mywebhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mywebhook
  name: mywebhook
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: mywebhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mywebhook
    spec:
      containers:
      - args:
        - -tlsCertFile=/etc/webhook/certs/cert.pem 
        - -tlsKeyFile=/etc/webhook/certs/key.pem
        - -alsologtostderr
        - -v=4
        - 2>&1
        command:
        - /bin/my-webhook
        image: my-webhook:latest
        imagePullPolicy: IfNotPresent
        name: webhook
        ports:
        - containerPort: 9443
          name: webhook
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/webhook/certs/
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: mywebhook
      serviceAccountName: mywebhook
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: mywebhook-secret
