resources:
- webhook.yaml
- service.yaml
- manifests.yaml
- rbac.yaml

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhook
  newName: k8s.gcr.io/multitenancy/externalip-webhook
  newTag: v1.0.0
