apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalip-validation-webhook
  namespace: externalip-validation-system
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externalip-validation-webhook
  namespace: externalip-validation-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externalip-validation-webhook
subjects:
- kind: ServiceAccount
  name: externalip-validation-webhook
  namespace: externalip-validation-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externalip-validation-webhook
  namespace: externalip-validation-system
