apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.test.k8s.io
spec:
  group: test.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: nginx-for-apiservice
    namespace: default
    port: 443
  version: v1beta1
  versionPriority: 100
