/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	versioned "github.com/greatlazyman/apiserver/pkg/apis/client/clientset/versioned"
	internalinterfaces "github.com/greatlazyman/apiserver/pkg/apis/client/informers/externalversions/internalinterfaces"
	transformationv1beta1 "github.com/greatlazyman/apiserver/pkg/apis/client/listers/transformation/v1beta1"
	apistransformationv1beta1 "github.com/greatlazyman/apiserver/pkg/apis/transformation/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// Base64Informer provides access to a shared informer and lister for
// Base64s.
type Base64Informer interface {
	Informer() cache.SharedIndexInformer
	Lister() transformationv1beta1.Base64Lister
}

type base64Informer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBase64Informer constructs a new informer for Base64 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBase64Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBase64Informer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBase64Informer constructs a new informer for Base64 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBase64Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TransformationV1beta1().Base64s(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TransformationV1beta1().Base64s(namespace).Watch(context.TODO(), options)
			},
		},
		&apistransformationv1beta1.Base64{},
		resyncPeriod,
		indexers,
	)
}

func (f *base64Informer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBase64Informer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *base64Informer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apistransformationv1beta1.Base64{}, f.defaultInformer)
}

func (f *base64Informer) Lister() transformationv1beta1.Base64Lister {
	return transformationv1beta1.NewBase64Lister(f.Informer().GetIndexer())
}
