//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	simpleio "github.com/greatlazyman/apiserver/pkg/apis/simple.io"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*simpleio.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Foo_To_simpleio_Foo(a.(*Foo), b.(*simpleio.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simpleio.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simpleio_Foo_To_v1beta1_Foo(a.(*simpleio.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooCondition)(nil), (*simpleio.FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooCondition_To_simpleio_FooCondition(a.(*FooCondition), b.(*simpleio.FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simpleio.FooCondition)(nil), (*FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simpleio_FooCondition_To_v1beta1_FooCondition(a.(*simpleio.FooCondition), b.(*FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooConfig)(nil), (*simpleio.FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooConfig_To_simpleio_FooConfig(a.(*FooConfig), b.(*simpleio.FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simpleio.FooConfig)(nil), (*FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simpleio_FooConfig_To_v1beta1_FooConfig(a.(*simpleio.FooConfig), b.(*FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooList)(nil), (*simpleio.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooList_To_simpleio_FooList(a.(*FooList), b.(*simpleio.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simpleio.FooList)(nil), (*FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simpleio_FooList_To_v1beta1_FooList(a.(*simpleio.FooList), b.(*FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooSpec)(nil), (*simpleio.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooSpec_To_simpleio_FooSpec(a.(*FooSpec), b.(*simpleio.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simpleio.FooSpec)(nil), (*FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simpleio_FooSpec_To_v1beta1_FooSpec(a.(*simpleio.FooSpec), b.(*FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooStatus)(nil), (*simpleio.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooStatus_To_simpleio_FooStatus(a.(*FooStatus), b.(*simpleio.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simpleio.FooStatus)(nil), (*FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simpleio_FooStatus_To_v1beta1_FooStatus(a.(*simpleio.FooStatus), b.(*FooStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Foo_To_simpleio_Foo(in *Foo, out *simpleio.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_FooSpec_To_simpleio_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_FooStatus_To_simpleio_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Foo_To_simpleio_Foo is an autogenerated conversion function.
func Convert_v1beta1_Foo_To_simpleio_Foo(in *Foo, out *simpleio.Foo, s conversion.Scope) error {
	return autoConvert_v1beta1_Foo_To_simpleio_Foo(in, out, s)
}

func autoConvert_simpleio_Foo_To_v1beta1_Foo(in *simpleio.Foo, out *Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_simpleio_FooSpec_To_v1beta1_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_simpleio_FooStatus_To_v1beta1_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_simpleio_Foo_To_v1beta1_Foo is an autogenerated conversion function.
func Convert_simpleio_Foo_To_v1beta1_Foo(in *simpleio.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_simpleio_Foo_To_v1beta1_Foo(in, out, s)
}

func autoConvert_v1beta1_FooCondition_To_simpleio_FooCondition(in *FooCondition, out *simpleio.FooCondition, s conversion.Scope) error {
	out.Type = simpleio.FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_v1beta1_FooCondition_To_simpleio_FooCondition is an autogenerated conversion function.
func Convert_v1beta1_FooCondition_To_simpleio_FooCondition(in *FooCondition, out *simpleio.FooCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_FooCondition_To_simpleio_FooCondition(in, out, s)
}

func autoConvert_simpleio_FooCondition_To_v1beta1_FooCondition(in *simpleio.FooCondition, out *FooCondition, s conversion.Scope) error {
	out.Type = FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_simpleio_FooCondition_To_v1beta1_FooCondition is an autogenerated conversion function.
func Convert_simpleio_FooCondition_To_v1beta1_FooCondition(in *simpleio.FooCondition, out *FooCondition, s conversion.Scope) error {
	return autoConvert_simpleio_FooCondition_To_v1beta1_FooCondition(in, out, s)
}

func autoConvert_v1beta1_FooConfig_To_simpleio_FooConfig(in *FooConfig, out *simpleio.FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Msg1 = in.Msg1
	return nil
}

// Convert_v1beta1_FooConfig_To_simpleio_FooConfig is an autogenerated conversion function.
func Convert_v1beta1_FooConfig_To_simpleio_FooConfig(in *FooConfig, out *simpleio.FooConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_FooConfig_To_simpleio_FooConfig(in, out, s)
}

func autoConvert_simpleio_FooConfig_To_v1beta1_FooConfig(in *simpleio.FooConfig, out *FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Msg1 = in.Msg1
	return nil
}

// Convert_simpleio_FooConfig_To_v1beta1_FooConfig is an autogenerated conversion function.
func Convert_simpleio_FooConfig_To_v1beta1_FooConfig(in *simpleio.FooConfig, out *FooConfig, s conversion.Scope) error {
	return autoConvert_simpleio_FooConfig_To_v1beta1_FooConfig(in, out, s)
}

func autoConvert_v1beta1_FooList_To_simpleio_FooList(in *FooList, out *simpleio.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]simpleio.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_FooList_To_simpleio_FooList is an autogenerated conversion function.
func Convert_v1beta1_FooList_To_simpleio_FooList(in *FooList, out *simpleio.FooList, s conversion.Scope) error {
	return autoConvert_v1beta1_FooList_To_simpleio_FooList(in, out, s)
}

func autoConvert_simpleio_FooList_To_v1beta1_FooList(in *simpleio.FooList, out *FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_simpleio_FooList_To_v1beta1_FooList is an autogenerated conversion function.
func Convert_simpleio_FooList_To_v1beta1_FooList(in *simpleio.FooList, out *FooList, s conversion.Scope) error {
	return autoConvert_simpleio_FooList_To_v1beta1_FooList(in, out, s)
}

func autoConvert_v1beta1_FooSpec_To_simpleio_FooSpec(in *FooSpec, out *simpleio.FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_v1beta1_FooConfig_To_simpleio_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_FooSpec_To_simpleio_FooSpec is an autogenerated conversion function.
func Convert_v1beta1_FooSpec_To_simpleio_FooSpec(in *FooSpec, out *simpleio.FooSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_FooSpec_To_simpleio_FooSpec(in, out, s)
}

func autoConvert_simpleio_FooSpec_To_v1beta1_FooSpec(in *simpleio.FooSpec, out *FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_simpleio_FooConfig_To_v1beta1_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_simpleio_FooSpec_To_v1beta1_FooSpec is an autogenerated conversion function.
func Convert_simpleio_FooSpec_To_v1beta1_FooSpec(in *simpleio.FooSpec, out *FooSpec, s conversion.Scope) error {
	return autoConvert_simpleio_FooSpec_To_v1beta1_FooSpec(in, out, s)
}

func autoConvert_v1beta1_FooStatus_To_simpleio_FooStatus(in *FooStatus, out *simpleio.FooStatus, s conversion.Scope) error {
	out.Phase = simpleio.FooPhase(in.Phase)
	out.Conditions = *(*[]simpleio.FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_FooStatus_To_simpleio_FooStatus is an autogenerated conversion function.
func Convert_v1beta1_FooStatus_To_simpleio_FooStatus(in *FooStatus, out *simpleio.FooStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_FooStatus_To_simpleio_FooStatus(in, out, s)
}

func autoConvert_simpleio_FooStatus_To_v1beta1_FooStatus(in *simpleio.FooStatus, out *FooStatus, s conversion.Scope) error {
	out.Phase = FooPhase(in.Phase)
	out.Conditions = *(*[]FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_simpleio_FooStatus_To_v1beta1_FooStatus is an autogenerated conversion function.
func Convert_simpleio_FooStatus_To_v1beta1_FooStatus(in *simpleio.FooStatus, out *FooStatus, s conversion.Scope) error {
	return autoConvert_simpleio_FooStatus_To_v1beta1_FooStatus(in, out, s)
}
